In [89]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import precision_score, recall_score, f1_score

### 1.1 Chargement du Dataset

In [90]:
df = pd.read_csv('../data/customer_churn_dataset.csv')

## 2 Préparation des Données

### 2.1 Définir les Features (X) et la Target (y)

In [91]:
# Target (variable à prédire)
y = df['Churn']

# Features (toutes les colonnes sauf la target)
X = df.drop('Churn', axis=1)

print(f"Features (X): {X.shape[1]} colonnes")
print(f"Colonnes: {list(X.columns)}")
print(f"\nTarget (y): {y.shape[0]} valeurs")

Features (X): 4 colonnes
Colonnes: ['Monthly_Usage', 'Customer_Support_Calls', 'Subscription_Length', 'Payment_Delay']

Target (y): 200 valeurs

### 2.2 Division en Données d'Entraînement et de Test

In [92]:
#entraînement (80 %) et de test (20 %)
X_train, X_test, y_train, y_test = train_test_split(
    X,y,
    test_size=0.2,
    random_state=42,
)

In [93]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

## 3 Entraînement du Modèle

### 3.1 Créer le Modèle de Régression Logistique

In [94]:
model = LogisticRegression(
    max_iter=1000,
    class_weight="balanced",
    random_state=42
)

### 3.2 Entraîner le Modèle

In [95]:
model.fit(X_train_scaled, y_train)

LogisticRegression(class_weight='balanced', max_iter=1000, random_state=42)

## 4 Évaluation du Modèle

### 4.1 Prédictions sur les Données de Test

In [96]:
y_pred = model.predict(X_test_scaled)

print("Prédictions effectuées!")
print(f"Nombre de prédictions: {len(y_pred)}")

Prédictions effectuées!
Nombre de prédictions: 40

### 4.2 Calcul de l'Accuracy

In [97]:
accuracy = accuracy_score(y_test, y_pred)

print(f"Accuracy du modèle: {accuracy * 100:.2f}%")

Accuracy du modèle: 87.50%

### 4.3 Matrice de Confusion

In [98]:
cm = confusion_matrix(y_test,y_pred)

print("Matrice de Confusion:")
print(cm)
print(f"\n  - Vrais Négatifs  (TN): {cm[0][0]} - Bien prédit 'Reste'")
print(f"  - Faux Positifs   (FP): {cm[0][1]} - Prédit 'Quitte' mais reste")
print(f"  - Faux Négatifs   (FN): {cm[1][0]} - Prédit 'Reste' mais quitte")
print(f"  - Vrais Positifs  (TP): {cm[1][1]} - Bien prédit 'Quitte'")

Matrice de Confusion:
[[ 9  3]
 [ 2 26]]

  - Vrais Négatifs  (TN): 9 - Bien prédit 'Reste'
  - Faux Positifs   (FP): 3 - Prédit 'Quitte' mais reste
  - Faux Négatifs   (FN): 2 - Prédit 'Reste' mais quitte
  - Vrais Positifs  (TP): 26 - Bien prédit 'Quitte'

### 4.4 Rapport de Classification

In [99]:
print("Rapport de Classification:")
print(classification_report(y_test,y_pred, target_names=['Reste (0)', 'Quitte (1)']))

Rapport de Classification:
              precision    recall  f1-score   support

   Reste (0)       0.82      0.75      0.78        12
  Quitte (1)       0.90      0.93      0.91        28

    accuracy                           0.88        40
   macro avg       0.86      0.84      0.85        40
weighted avg       0.87      0.88      0.87        40

### 4.5 Calculer les métriques

In [100]:
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print(f"Precision: {precision*100:.2f}%")
print(f"Recall: {recall*100:.2f}%")
print(f"F1-Score: {f1*100:.2f}%")

Precision: 89.66%
Recall: 92.86%
F1-Score: 91.23%

### 4.5 Coefficients du Modèle

In [101]:
print("Importance des Features (Coefficients):")
for feature, coef in zip(X.columns, model.coef_[0]):
    print(f"  {feature}: {coef:+.4f}")

Importance des Features (Coefficients):
  Monthly_Usage: -0.1637
  Customer_Support_Calls: +1.8852
  Subscription_Length: +0.2810
  Payment_Delay: +2.6722

## 5 Prédictions sur de Nouveaux Clients

### 5.1 Créer de Nouveaux Clients

In [102]:
nouveaux_clients = pd.DataFrame({
    'Monthly_Usage': [100, 450, 200],
    'Customer_Support_Calls': [8, 1, 5],
    'Subscription_Length': [12, 40, 24],
    'Payment_Delay': [25, 3, 15]
})

print("Nouveaux clients à prédire:")
nouveaux_clients

Nouveaux clients à prédire:

   Monthly_Usage  Customer_Support_Calls  Subscription_Length  Payment_Delay
0            100                       8                   12             25
1            450                       1                   40              3
2            200                       5                   24             15

Normaliser les nouveaux clients

In [103]:
nouveaux_clients_scaled = scaler.transform(nouveaux_clients)

predictions = model.predict(nouveaux_clients_scaled)

print("Prédictions:")
for i, pred in enumerate(predictions):
    status = "Quitte (1)" if pred == 1 else "Reste (0)"
    print(f"  Client {i+1}: {status}")

Prédictions:
  Client 1: Quitte (1)
  Client 2: Reste (0)
  Client 3: Quitte (1)

### 5.2 Faire les Prédictions

In [104]:
predictions = model.predict(nouveaux_clients_scaled)

print("Prédictions:")
for i, pred in enumerate(predictions):
    status = "Quitte (1)" if pred == 1 else "Reste (0)"
    print(f"  Client {i+1}: {status}")

Prédictions:
  Client 1: Quitte (1)
  Client 2: Reste (0)
  Client 3: Quitte (1)

### 5.3 Probabilités de Prédiction

In [105]:
probabilites = model.predict_proba(nouveaux_clients_scaled)

print("Probabilités de Churn:")
for i, prob in enumerate(probabilites):
    print(f"  Client {i+1}: {prob[0]*100:.1f}% Reste | {prob[1]*100:.1f}% Quitte")

Probabilités de Churn:
  Client 1: 0.1% Reste | 99.9% Quitte
  Client 2: 99.0% Reste | 1.0% Quitte
  Client 3: 13.5% Reste | 86.5% Quitte

### 5.4 Résumé des Prédictions

In [106]:
resultats = nouveaux_clients.copy()

resultats['Prediction'] = predictions
resultats['Proba_Reste'] = probabilites[:, 0]
resultats['Proba_Quitte'] = probabilites[:, 1]

print("Tableau récapitulatif:")
resultats

Tableau récapitulatif:

,Monthly_Usage,Customer_Support_Calls,Subscription_Length,Payment_Delay,Prediction,Proba_Reste,Proba_Quitte
0,100,8,12,25,1,0.001035,0.998965
1,450,1,40,3,0,0.989529,0.010471
2,200,5,24,15,1,0.134943,0.865057

### 5.5 Explication des Prédictions

In [107]:
print("Explication des prédictions:")
print("="*50)

for i in range(len(nouveaux_clients)):
    client = nouveaux_clients.iloc[i]
    pred = "QUITTE" if predictions[i] == 1 else "RESTE"
    prob = probabilites[i][1] * 100

    print(f"\nClient {i+1}: {pred} ({prob:.1f}% de chance de quitter)")
    print(f"  - Appels support : {client['Customer_Support_Calls']}")
    print(f"  - Retard paiement: {client['Payment_Delay']} jours")

    if predictions[i] == 1:
        raisons = []
        if client['Customer_Support_Calls'] >= 5:
            raisons.append("beaucoup d'appels au support")
        if client['Payment_Delay'] >= 15:
            raisons.append("retard de paiement élevé")
        if raisons:
            print(f"  → Raisons: {', '.join(raisons)}")
    else:
        print(f"  → Client fidèle")

Explication des prédictions:
==================================================

Client 1: QUITTE (99.9% de chance de quitter)
  - Appels support : 8
  - Retard paiement: 25 jours
  → Raisons: beaucoup d'appels au support, retard de paiement élevé

Client 2: RESTE (1.0% de chance de quitter)
  - Appels support : 1
  - Retard paiement: 3 jours
  → Client fidèle

Client 3: QUITTE (86.5% de chance de quitter)
  - Appels support : 5
  - Retard paiement: 15 jours
  → Raisons: beaucoup d'appels au support, retard de paiement élevé

##  6 Interprétation et Storytelling

### 6.1 Quels clients sont plus susceptibles de partir ?

In [108]:
print("Profil des clients à risque de CHURN:")
print("="*50)
print("""
Les clients les plus susceptibles de partir sont ceux qui:

  1. Ont un RETARD DE PAIEMENT élevé (> 15 jours)
  2. Appellent SOUVENT le support (> 5 appels)

Ces deux facteurs combinés indiquent une insatisfaction
du client et un risque élevé de départ.
""")

Profil des clients à risque de CHURN:
==================================================

Les clients les plus susceptibles de partir sont ceux qui:

  1. Ont un RETARD DE PAIEMENT élevé (> 15 jours)
  2. Appellent SOUVENT le support (> 5 appels)

Ces deux facteurs combinés indiquent une insatisfaction
du client et un risque élevé de départ.

### 6.2 Quelle feature est la plus importante ?

In [109]:
print("Importance des Features:")
print("="*50)

# Trier par valeur absolue des coefficients
importance = pd.DataFrame({
    'Feature': X.columns,
    'Coefficient': model.coef_[0]
})

importance['Importance'] = abs(importance['Coefficient'])
importance = importance.sort_values('Importance', ascending=False)

for _,row in importance.iterrows():
    print(f"  {row['Feature']:25}: {row['Coefficient']:+.4f}")

print(f"\n→ Feature la plus importante: {importance.iloc[0]['Feature']}")

Importance des Features:
==================================================
  Payment_Delay            : +2.6722
  Customer_Support_Calls   : +1.8852
  Subscription_Length      : +0.2810
  Monthly_Usage            : -0.1637

→ Feature la plus importante: Payment_Delay

### 6.3 Peut-on faire confiance au modèle à 100% ?

In [110]:
print("Peut-on faire confiance au modèle à 100% ?")
print("="*50)
print(f"""
NON, on ne peut pas faire confiance à 100%.

Raisons:
  1. Accuracy = {accuracy*100:.2f}% (pas 100%)
  2. Le modèle fait des erreurs
  3. Dataset petit (200 clients seulement)
  4. Données historiques ≠ Comportement futur

Le modèle est un OUTIL D'AIDE à la décision,
pas une vérité absolue.
""")

Peut-on faire confiance au modèle à 100% ?
==================================================

NON, on ne peut pas faire confiance à 100%.

Raisons:
  1. Accuracy = 87.50% (pas 100%)
  2. Le modèle fait des erreurs
  3. Dataset petit (200 clients seulement)
  4. Données historiques ≠ Comportement futur

Le modèle est un OUTIL D'AIDE à la décision,
pas une vérité absolue.

### 6.4 Comment l'entreprise peut-elle réduire le churn ?

In [111]:
print("Recommandations pour réduire le Churn:")
print("="*50)
print("""
1. RETARD DE PAIEMENT:
   - Envoyer des rappels avant l'échéance
   - Offrir des options de paiement flexibles
   - Contacter les clients avec retard > 10 jours

2. APPELS AU SUPPORT:
   - Améliorer la qualité du service client
   - Résoudre les problèmes dès le premier appel
   - Contacter proactivement les clients qui appellent souvent

3. CLIENTS À RISQUE:
   - Identifier les clients avec Payment_Delay > 15 ET Support_Calls > 5
   - Leur offrir des avantages pour les fidéliser
   - Appel personnalisé pour comprendre leurs problèmes

4. PRÉVENTION:
   - Utiliser ce modèle pour prédire le churn mensuellement
   - Agir AVANT que le client parte
""")

Recommandations pour réduire le Churn:
==================================================

1. RETARD DE PAIEMENT:
   - Envoyer des rappels avant l'échéance
   - Offrir des options de paiement flexibles
   - Contacter les clients avec retard > 10 jours

2. APPELS AU SUPPORT:
   - Améliorer la qualité du service client
   - Résoudre les problèmes dès le premier appel
   - Contacter proactivement les clients qui appellent souvent

3. CLIENTS À RISQUE:
   - Identifier les clients avec Payment_Delay > 15 ET Support_Calls > 5
   - Leur offrir des avantages pour les fidéliser
   - Appel personnalisé pour comprendre leurs problèmes

4. PRÉVENTION:
   - Utiliser ce modèle pour prédire le churn mensuellement
   - Agir AVANT que le client parte